name: Testcontainers CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:

    container:
      image: docker:27.3.1-dind
      options: --security-opt seccomp=unconfined
      privileged: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Install GCC and dependencies
        run: |
          apk add build-base

      - name: Run tests
        env:
          CGO_ENABLED: "1"
        run: |
          go test ./... -v