name: Testcontainers CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:23.0.6-dind
        privileged: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Run tests with TigerBeetle
        env:
          DOCKER_HOST: tcp://localhost:2375
        run: |
          go test ./... -v